### ISSUE TITLE
Todo from Oversite Meeting 2021.01.25

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#92]
- [x] language cert as full width
- [x] humanities plus same width, but internat. full width
- [x] News article blurb should be instead of whitespace after news article
- [x] "explore majors" to catalog
