### ISSUE TITLE
TODO from oversite meeting 2020.02.01

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#98]
- [x] News story to have low enough height to have the text below the image be visible without scrolling
- [ ] BYU logo higher res? https://github.com/BYU-ODH/wp-humanities-byu/issues/121
- [x] Article 1920 x 1080
- [x] Remove hover-opacity on news link
- [x] Humanities plus image is on dev but not staging but
- [x] Spacing above the 3 (ic, writing, studyabroad) is good; make it match below
- [ ] News to be "featured" not "recent" https://github.com/BYU-ODH/wp-humanities-byu/issues/122 
- [ ] Student Resources should be a nav dropdown https://github.com/BYU-ODH/wp-humanities-byu/issues/106
  - [ ] intern/studyabroad are two separate things 
- [x] Departments page: get rid of images; just make it a list
- [ ] Directory 
  - [x] name should be black, as the subtitle
  - [x] Blue-gray should be according to the byu theme
  - [x] All gray should be different (be the byu blue gray)
  - [x] Match colors from lifescience.byu.edu/faculty-staff
  - [x] Make all colors from the web. See BYU web palette at https://brand.byu.edu/web-toolkit/color/
  - [ ] Remove awards from the dept filter list (humwebhelp)
  - [ ] Remove directory-empty "centers" (humwebhelp)
- [ ] Searchbox needs fixing yet https://github.com/BYU-ODH/wp-humanities-byu/issues/52
- [x] Remove "more news" button
